### ISSUE TITLE
【3.5.0】cant get https://gitlab.cocos.net/publics/runtime-web-adapter

### ISSUE THREAD

**Issue by ankye** [cocos/cocos-engine#10997]
### Cocos Creator version

3.5.0

### System information

mac and win11

### Issue description

F:\work\cocos-engine>npm install

> typedoc-plugin-cc@file:scripts/typedoc-plugin postinstall F:\work\cocos-engine\node_modules\typedoc-plugin-cc
> npm run build

> typedoc-plugin-cc@1.0.0 build F:\work\cocos-engine\node_modules\typedoc-plugin-cc
> tsc

> cocos-creator@3.6.0 postinstall F:\work\cocos-engine
> gulp build-debug-infos && gulp build-declarations && npm run fetch-ral && npm run install:typedoc-plugin

[00:38:41] Using gulpfile F:\work\cocos-engine\gulpfile.js
[00:38:41] Starting 'build-debug-infos'...
[00:38:41] Finished 'build-debug-infos' after 18 ms
[00:38:41] Using gulpfile F:\work\cocos-engine\gulpfile.js
[00:38:41] Starting 'build-declarations'...
Typescript version: 4.3.5
With index: true
With exports: false
With editor exports: true
Generating...
F:\work\cocos-engine\tsconfig.json (15,5): Option 'outFile' cannot be specified with option 'isolatedModules'.
Bundling...
Failed to resolve type import("cocos/core/gfx").Texture, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Sampler, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").SamplerInfo, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core").Size, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Attribute, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Attribute, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Attribute, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Attribute, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Attribute, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Attribute, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Attribute, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").InputAssembler, There is no symbol info.
Failed to resolve type import("cocos/core/math").Size, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").DescriptorSetLayout, There is no symbol info.
Failed to resolve type import("cocos/core/renderer/scene").Camera, There is no symbol info.
Failed to resolve type import("cocos/core/renderer/scene").Camera, There is no symbol info.
Culling interface: 965.797ms
[00:39:02] Finished 'build-declarations' after 21 s

> cocos-creator@3.6.0 fetch-ral F:\work\cocos-engine
> node ./scripts/fetch-ral.js

Checking ral file...

Cleaning old runtime adapter...

Remove ral directory: 'F:/work/cocos-engine/scripts/runtime-web-adapter'

Running command: 'git clone https://gitlab.cocos.net/publics/runtime-web-adapter' in 'F:/work/cocos-engine/scripts/runtime-web-adapter'

Cloning into 'runtime-web-adapter'...

fatal: unable to access 'https://gitlab.cocos.net/publics/runtime-web-adapter/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitlab.cocos.net:443

Running command: 'git checkout for-creator-3' in 'F:/work/cocos-engine/scripts/runtime-web-adapter'

Running command: 'git reset --hard 03196a40cf71174662ae36c25954ea3761320738' in 'F:/work/cocos-engine/scripts/runtime-web-adapter'

Running command: 'npm install' in 'F:/work/cocos-engine/scripts/runtime-web-adapter'

Running command: 'gulp' in 'F:/work/cocos-engine/scripts/runtime-web-adapter'

Copy files from 'F:/work/cocos-engine/scripts/runtime-web-adapter' to 'F:/work/cocos-engine/platforms/runtime'

Fetch ral failed Error: ENOENT: no such file or directory, copyfile 'F:/work/cocos-engine/scripts/runtime-web-adapter/dist/common/web-adapter.js' -> 'F:/work/cocos-engine/platforms/runtime/common/web-adapter.js'
    at Object.copyFileSync (fs.js:1991:3)
    at F:\work\cocos-engine\scripts\fetch-ral.js:90:12
    at Array.forEach (<anonymous>)
    at copyRal (F:\work\cocos-engine\scripts\fetch-ral.js:87:46)
    at F:\work\cocos-engine\scripts\fetch-ral.js:153:9 {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'F:/work/cocos-engine/scripts/runtime-web-adapter/dist/common/web-adapter.js',
  dest: 'F:/work/cocos-engine/platforms/runtime/common/web-adapter.js'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocos-creator@3.6.0 fetch-ral: `node ./scripts/fetch-ral.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cocos-creator@3.6.0 fetch-ral script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ankye\scoop\persist\nodejs\cache\_logs\2022-05-07T16_40_29_183Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocos-creator@3.6.0 postinstall: `gulp build-debug-infos && gulp build-declarations && npm run fetch-ral && npm run install:typedoc-plugin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cocos-creator@3.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ankye\scoop\persist\nodejs\cache\_logs\2022-05-07T16_40_29_240Z-debug.log

### Steps to reproduce

get the code and then npm install

**Comment by PPpro** [comment]
fixed here

https://github.com/cocos/cocos-engine/pull/11001
https://github.com/cocos/cocos-engine/pull/11013

**Comment by Ronsku** [comment]
@PPpro is it really fixed?
I tried 3.6.0 branch and I still get these errors
![image](https://user-images.githubusercontent.com/7983358/171964362-f51ca423-5b4c-4d4d-b7da-9bdd14885890.png)

this is from the "postinstall" and "build" npm runs. What do you suggest to do to fix this?

**Comment by PPpro** [comment]
https://github.com/cocos/cocos-engine/pull/11001
https://github.com/cocos/cocos-engine/pull/11013

This 2 PR doesn't fix the issue you mentioned, it fix the error like:
```
Cloning into 'runtime-web-adapter'...

fatal: unable to access 'https://gitlab.cocos.net/publics/runtime-web-adapter/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitlab.cocos.net:443
```

And sorry the issue you mentioned is not easy to solve at present  :(  
but it should have little impact

This issue could be solved after engine modularization，which is a long term task

@Ronsku

**Comment by Ronsku** [comment]
@PPpro How do you run and develop on the engine then?
I would just get it to run since I really need to look and try to modify the engine to get rid of dead code in a 2D game.
I'm here referring to my ticket: https://github.com/cocos/cocos-engine/issues/10354

**Comment by PPpro** [comment]
> How do you run and develop on the engine then?
I would just get it to run since I really need to look and try to modify the engine to get rid of dead code in a 2D game.

```
Failed to resolve type import("cocos/core/gfx").Texture, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").Sampler, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").SamplerInfo, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
Failed to resolve type import("cocos/core/gfx").BlendFactor, There is no symbol info.
....
```
All these log should be warning messages to generate cc.d.ts,
they are not the error messages that blocking you from running the engine.

I am not quite sure what issue you encounter when you are running the engine ?

**Comment by Ronsku** [comment]
@PPpro Thanks for your swift responses!
I see, I thought that was required to run it properly. Because when I start the engine with `npm run server` It does start up the server but it is missing a bunch of files:
![image](https://user-images.githubusercontent.com/7983358/172120015-c6bd8051-8359-4342-a3c4-40189b3535a7.png)

**Comment by Ronsku** [comment]
@PPpro Here is from the terminal
![image](https://user-images.githubusercontent.com/7983358/172121510-e2b08a1c-e1c3-4475-b0cd-bcc3e952148c.png)

**Comment by PPpro** [comment]
@Ronsku Oh, sorry, we have not maintained the playground for a long time, the `npm run server` is not working now.

For now, if you want to run the custom engine, you can try on the  docs **Engine Customization Workflow**
https://docs.cocos.com/creator/manual/en/advanced-topics/engine-customization.html?h=customiz

**Comment by Ronsku** [comment]
@PPpro ahaa, I see. Thanks!

**Comment by mzvast** [comment]
> @Ronsku Oh, sorry, we have not maintained the playground for a long time, the `npm run server` is not working now.
> 
> For now, if you want to run the custom engine, you can try on the docs **Engine Customization Workflow** https://docs.cocos.com/creator/manual/en/advanced-topics/engine-customization.html?h=customiz

Oh my god. I was trying to figure out how to run playground with no luck.

Maybe we should warning devs somewhere before they came into this issue.
