### ISSUE TITLE
Spine Skeleton Enable Batch is not working

### ISSUE THREAD

**Issue by cad-icandy** [cocos/cocos-engine#15812]
### Cocos Creator version

3.6.2

### System information

mac OS 12.6.1

### Issue description

I've ticked "Enable Batch" is Skeleton component but when I preview on web, the draw call is still high. The exported spine asset has only 1 atlas.

I'm aware that if the spine has different materials (default and additive) will break the batching but according to Spine's [doc]([Advanced - Premultiplied vs Straight Alpha Export](http://en.esotericsoftware.com/spine-unity#Advanced---Premultiplied-vs-Straight-Alpha-Export)), it shouldn't happened. I'm using premultiplied alpha setting too.

`Premultiplied alpha workflow offers some advantages over straight alpha, no additional draw calls for additive-blended attachments and better mip-map generation being two of them.`

Any idea why is this happening?

### Steps to reproduce

as described in description

**Comment by pandamicro** [comment]
Please update to 3.8, it should have been fixed

**Comment by cad-icandy** [comment]
I've updated to v3.8 and no, it's not working. I'm still seeing high draw calls despite I only use additive in Spine Editor.

**Comment by pandamicro** [comment]
I reopened it, we will check it in v3.8.1

**Comment by Canvasfull** [comment]
> I've updated to v3.8 and no, it's not working. I'm still seeing high draw calls despite I only use additive in Spine Editor.

Can you provide your demo? I checked that 3.8.0 is already supported.

**Comment by cad-icandy** [comment]
Here you go
https://file.io/pJg764srkK9R

**Comment by cad-icandy** [comment]
any update on this?

**Comment by cad-icandy** [comment]
I saw 3.8.1 has been released but I don't see this being mentioned? So I assume this is still not fixed in 3.8.1?

**Comment by bofeng-song** [comment]
> I saw 3.8.1 has been released but I don't see this being mentioned? So I assume this is still not fixed in 3.8.1?

Could you upload your demo or follow cocos's [API doc ](https://docs.cocos.com/creator/manual/zh/editor/components/spine.html)

**Comment by bofeng-song** [comment]
> I saw 3.8.1 has been released but I don't see this being mentioned? So I assume this is still not fixed in 3.8.1?

What's your target platform? IOS or mac ?
Currently, we may only support the web version.

**Comment by bofeng-song** [comment]
The self-test for the batch merge functionality is working as expected. If any issues are identified during validation on version 382, please kindly provide feedback.

**Comment by HelloAndGoodbye0** [comment]
The creator did not solve the problem of a high spine draw call. This is because there are different blending modes in the spine, which interrupts the batching. However, the unity draw call is very low. The creator should solve the problem.
