### ISSUE TITLE
UIOpacity doesn't effect the child node when it becomes active the first time in native.

### ISSUE THREAD

**Issue by AkshayshettyS** [cocos/cocos-engine#17419]
### Cocos Creator version

3.8.2, 3.8.3

### System information

All android and iOS devices

### Issue description

When a node has UIOpacity and a child that is initially inactive, UIOpacity does not apply to the child node when it is enabled for the first time in native platforms (In web it works).

### Steps to reproduce

- Set a child node to inactive inside the parent node with UIOpacity.
- Change the UIOpacity value.
- Activate the child node.
- Observe that the opacity value is not applied to the child node when it is activated for the first time.

### Minimal reproduction project

[UIOpacity.zip](https://github.com/user-attachments/files/16387397/UIOpacity.zip)

**Comment by yoki0805** [comment]
> When a node has UIOpacity and a child that is initially inactive, UIOpacity does not apply to the child node when it is enabled for the first time in native platforms (In web it works).

In this case (Creator v3.8.3), when the child node is enabled for the first time, its node._uiProps.uiComp hasn't been set yet.
It causes the if statement below to not work.

A quick test:
Change the code on line 107 to `const render = node.getComponent(UIRenderer);`.
It will be fixed.

https://github.com/cocos/cocos-engine/blob/7087c23f72a26709a2431d709a16c2275dec237f/cocos/2d/components/ui-opacity.ts#L107-L127

**Comment by qiuguohua** [comment]
This issue was fixed in 3.8.4, the community version is available for testing.
Another problem I found is that you need to be active first and then set the opacity.

**Comment by AkshayshettyS** [comment]
Hello @qiuguohua in 3.8.4 the opacity value is applied to the sprite but label still doesn't take the opacity.
I just checked updating the above reproduction project to 3.8.4.

**Comment by qiuguohua** [comment]
@AkshayshettyS Another problem I found is that you need to be active first and then set the opacity.

**Comment by AkshayshettyS** [comment]
@qiuguohua The parent node which I am setting the opacity is always active you mean I should keep the child active as well?

**Comment by qiuguohua** [comment]
```
          this.label.node.parent.parent.getComponent(UIOpacity).opacity = 0.0000001;
          this.label.node.parent.active = true;
change to :
          this.label.node.parent.active = true;
          this.label.node.parent.parent.getComponent(UIOpacity).opacity = 0.0000001;
```

**Comment by AkshayshettyS** [comment]
This is the same issue I mentioned above that is if a child becomes active first time after the opacity of the parent is set it does not affect the children the first time.
Here the output in web and native are different right.

**Comment by qiuguohua** [comment]
I tested the web and windows display is the same!
Show a blue background at the end? Because this transparency is almost 0

**Comment by AkshayshettyS** [comment]
My code is kind of like this
```
this.label.node.parent.parent.getComponent(UIOpacity).opacity = 0.0000001;
this.label.node.parent.active = true;

```
In my case the childrens will be inactive from load and I am setting the opacity of the parent, then after some time enabling the child in the scene. 
Is this the wrong way of doing this?

> This is the same issue I mentioned above that is if a child becomes active first time after the opacity of the parent is set it does not affect the children the first time. Here the output in web and native are different right.

I meant this in my case.

**Comment by qiuguohua** [comment]
I see, there is a problem with the current implementation, making sure the node is active when setting the opacity.

You can temporarily set active to true and then set opacity, and then set active to false.

I'll think about how to avoid that later.

**Comment by yoki0805** [comment]
Please take a look.
[Fix UIOpacity issue on native platform](https://github.com/cocos/cocos-engine/pull/17503)

@qiuguohua

**Comment by qiuguohua** [comment]
It's great, thanks for doing it! @yoki0805
